---
abstract: 'Perl class for video frames pattern generating.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  List::MoreUtils: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Video-Pattern
no_index:
  directory:
    - inc
    - t
requires:
  Cwd: 0
  English: 0
  Exporter: 0
  List::MoreUtils: 0
  Readonly: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Video-Pattern
  homepage: https://github.com/tupinek/Video-Pattern
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Video-Pattern
version: 0.01
